// 全部为演示假数据，不含真实账户、消耗、考核价或内部人员信息。
export const campaignRows = [
  {
    id: 1,
    header: "夏季拉新计划",
    type: "账户巡检",
    status: "达标",
    target: "96%",
    limit: "90%",
    reviewer: "优化师 A",
  },
  {
    id: 2,
    header: "高潜账户扩量",
    type: "扩量任务",
    status: "进行中",
    target: "82%",
    limit: "85%",
    reviewer: "优化师 B",
  },
  {
    id: 3,
    header: "素材疲劳排查",
    type: "素材诊断",
    status: "达标",
    target: "91%",
    limit: "88%",
    reviewer: "优化师 A",
  },
  {
    id: 4,
    header: "超成本账户复核",
    type: "风险处理",
    status: "进行中",
    target: "77%",
    limit: "90%",
    reviewer: "待分配",
  },
  {
    id: 5,
    header: "新品测试矩阵",
    type: "测试任务",
    status: "未开始",
    target: "68%",
    limit: "80%",
    reviewer: "优化师 C",
  },
  {
    id: 6,
    header: "回传差异对账",
    type: "Gap 对账",
    status: "达标",
    target: "98%",
    limit: "95%",
    reviewer: "优化师 B",
  },
  {
    id: 7,
    header: "周末时段调优",
    type: "时段策略",
    status: "进行中",
    target: "86%",
    limit: "88%",
    reviewer: "优化师 A",
  },
  {
    id: 8,
    header: "低效素材下线建议",
    type: "素材诊断",
    status: "达标",
    target: "93%",
    limit: "90%",
    reviewer: "待分配",
  },
  {
    id: 9,
    header: "账户余额预警",
    type: "账户巡检",
    status: "进行中",
    target: "79%",
    limit: "92%",
    reviewer: "优化师 C",
  },
  {
    id: 10,
    header: "任务目标达成复盘",
    type: "经营复盘",
    status: "达标",
    target: "95%",
    limit: "90%",
    reviewer: "优化师 B",
  },
  {
    id: 11,
    header: "高转化素材复用",
    type: "素材协作",
    status: "进行中",
    target: "84%",
    limit: "86%",
    reviewer: "优化师 A",
  },
  {
    id: 12,
    header: "异常消耗趋势核验",
    type: "风险处理",
    status: "未开始",
    target: "71%",
    limit: "89%",
    reviewer: "待分配",
  },
];
