# PICPLOT (PP) 项目知识库

欢迎来到 PICPLOT 项目知识库。本库旨在记录项目架构、业务流程、技术细节及开发运维规范。

## 📁 目录导航

### [1. 🚀 快速开始 (Quick Start)](01_quickstart/onboarding.md)
*   [环境搭建与开发配置](01_quickstart/environment.md)
*   [项目愿景与核心概念](01_quickstart/onboarding.md)
*   [**项目全貌总结 (Project Summary)**](picplot_project/project_summary.md)
*   [**Vidu 迁移需求 (Current Task)**](picplot_project/vidu_migration_requirement.md)

### [2. ⛓️ 核心工作流 (Core Workflows)](02_workflows/overview.md)
*   [工作流概览与编排逻辑](02_workflows/overview.md)
*   [实体抽取 (Novel Entity)](02_workflows/novel_entity.md)
*   [分镜脚本生成 (Shot Script)](02_workflows/shot_script.md)
*   [分镜图生成 (Shot Pic)](02_workflows/shot_pic.md)
*   [分镜视频生成 (Shot Video)](02_workflows/shot_video.md)
*   [TTS 语音合成](02_workflows/tts.md)
*   [字幕擦除 (Subtitle Erase)](02_workflows/subtitle_erase.md)
*   [视频最终合成 (Video Merge)](02_workflows/re_video.md)

### [3. 🤖 AI 模型与 Prompt 仓库](03_ai_models/models_matrix.md)
*   [AI 模型分工矩阵](03_ai_models/models_matrix.md)
*   [Prompt 编写与优化指南](03_ai_models/prompts_guide.md)

### [4. 📊 数据架构与状态机](04_data_architecture/er_diagram.md)
*   [数据库 ER 图与核心表说明](04_data_architecture/er_diagram.md)
*   [Episode 状态机与流转逻辑](04_data_architecture/state_machines.md)

### [5. ☁️ 基础设施与云服务](05_infrastructure/cloud_services.md)
*   [OSS 存储规范](05_infrastructure/oss_spec.md)
*   [ICE 视频处理规范](05_infrastructure/cloud_services.md)
*   [认证与安全 (BUC SSO)](05_infrastructure/auth.md)

### [6. 🛠️ 运维与排错 (Troubleshooting)](06_troubleshooting/common_issues.md)
*   [任务调度器 (Scheduler) 逻辑](06_troubleshooting/scheduler_logic.md)
*   [常见问题与排查手册](06_troubleshooting/common_issues.md)

---
*Generated by 笼中雀 (AI Assistant) on 2026-02-09*