export const UI_SOURCES = [
  {
    id: "shadcn",
    name: "shadcn/ui",
    catalogMode: "registry-plus-variant-index",
    catalogUrls: [
      "https://ui.shadcn.com/r/styles/new-york-v4/registry.json",
      "https://ui.shadcn.com/r/index.json",
      "https://ui.shadcn.com/r/config.json",
    ],
    discoveryUrls: [
      "https://ui.shadcn.com/r/registries.json",
      "https://ui.shadcn.com/docs/figma",
    ],
    docsUrl: "https://ui.shadcn.com/docs",
    previewUrl: "https://ui.shadcn.com/docs/components",
    repositoryUrl: "https://github.com/shadcn-ui/ui",
    licenseUrl: "https://github.com/shadcn-ui/ui/blob/main/LICENSE.md",
    license: "MIT for shadcn first-party Registry assets",
    guides: [
      "https://ui.shadcn.com/docs/registry/registry-index",
      "https://github.com/shadcn-ui/ui/blob/main/skills/shadcn/SKILL.md",
      "https://github.com/shadcn-ui/ui/blob/main/skills/shadcn/customization.md",
      "https://github.com/shadcn-ui/ui/blob/main/skills/shadcn/registry.md",
    ],
    coverage: "complete-new-york-v4-plus-logical-index",
    coverageNote:
      "471-entry New York v4 Registry plus two current base-specific UI items from r/index.json; 24 preset variants are recorded as a matrix, not miscounted as unique components.",
    redistribution: "permitted-with-license",
  },
  {
    id: "coss",
    name: "coss/ui",
    catalogMode: "registry",
    catalogUrls: ["https://coss.com/ui/r/registry.json"],
    docsUrl: "https://coss.com/ui/docs",
    previewUrl: "https://coss.com/ui/particles",
    repositoryUrl: "https://github.com/cosscom/coss",
    licenseUrl: "https://github.com/cosscom/coss/blob/main/LICENSING.md",
    license: "MIT for apps/ui; repository default is AGPL-3.0",
    guides: [
      "https://coss.com/ui/docs/get-started",
      "https://coss.com/ui/docs/styling",
      "https://coss.com/ui/docs/radix-shadcn-migration",
      "https://coss.com/ui/docs/changelog",
      "https://coss.com/ui/docs/skills",
      "https://coss.com/ui/llms.txt",
    ],
    coverage: "complete-current-registry",
    coverageNote: "Current coss Registry is complete; legacy Origin is kept as a separate catalog.",
    redistribution: "MIT-only-for-apps-ui-scope",
  },
  {
    id: "coss-origin",
    name: "coss Origin",
    catalogMode: "repository-tree-plus-category-map",
    catalogUrls: [
      "https://api.github.com/repos/cosscom/coss/git/trees/main?recursive=1",
      "https://raw.githubusercontent.com/cosscom/coss/main/apps/origin/config/components.ts",
    ],
    docsUrl: "https://coss.com/origin",
    previewUrl: "https://coss.com/origin",
    repositoryUrl: "https://github.com/cosscom/coss/tree/main/apps/origin",
    licenseUrl: "https://github.com/cosscom/coss/blob/main/LICENSING.md",
    license: "MIT for apps/origin; repository default is AGPL-3.0",
    guides: [
      "https://coss.com/ui/docs/roadmap",
      "https://github.com/cosscom/coss/blob/main/apps/origin/README.md",
    ],
    coverage: "complete-legacy-registry",
    coverageNote: "646 public Origin Registry JSON items: 599 components plus 47 support assets; legacy/limited-support, not paid.",
    redistribution: "MIT-only-for-apps-origin-scope",
  },
  {
    id: "reui",
    name: "ReUI",
    catalogMode: "registry-plus-llms-index-plus-dynamic-icon-pages",
    catalogUrls: [
      "https://reui.io/r/registry.json",
      "https://reui.io/llms.txt",
      "https://reui.io/r/styles/index.json",
    ],
    docsUrl: "https://reui.io/docs",
    previewUrl: "https://reui.io/components",
    repositoryUrl: "https://github.com/keenthemes/reui",
    licenseUrl: "https://reui.io/legal/license",
    license: "MIT for public free source; ReUI commercial license for Pro/Ultimate assets",
    guides: [
      "https://reui.io/docs/get-started",
      "https://reui.io/docs/registry",
      "https://reui.io/docs/styling",
      "https://reui.io/docs/license-setup",
      "https://reui.io/docs/changelog",
      "https://reui.io/llms.txt",
    ],
    coverage: "complete-official-llms-index",
    coverageNote:
      "Registry plus official llms.txt covers free examples/modules/hooks, 518 Pro blocks, 638 icon concepts and 10 Ultimate templates; 16 concrete Base/Radix style variants are a separate matrix.",
    redistribution: "free-mit-paid-no-source-redistribution",
  },
  {
    id: "tremor",
    name: "Tremor Raw, Blocks and Templates",
    catalogMode: "repository-index-plus-template-page",
    catalogUrls: [
      "https://api.github.com/repos/tremorlabs/tremor/git/trees/main?recursive=1",
      "https://api.github.com/repos/tremorlabs/tremor-blocks/git/trees/main?recursive=1",
      "https://blocks.tremor.so/templates",
    ],
    docsUrl: "https://www.tremor.so/docs",
    previewUrl: "https://blocks.tremor.so/blocks",
    repositoryUrl: "https://github.com/tremorlabs",
    licenseUrl: "https://github.com/tremorlabs/tremor/blob/main/LICENSE",
    license: "Apache-2.0 for Tremor Raw; MIT for Blocks/current full templates",
    guides: [
      "https://www.tremor.so/docs/getting-started/installation",
      "https://blocks.tremor.so/blocks",
      "https://blocks.tremor.so/templates",
      "https://github.com/tremorlabs/tremor",
      "https://github.com/tremorlabs/tremor-blocks",
    ],
    coverage: "complete-current-public-surfaces",
    coverageNote:
      "40 Raw capabilities/39 source dirs, five utilities, 323 Blocks, six official templates and one related dashboard OSS variant.",
    redistribution: "verify-subproject-license",
  },
  {
    id: "tremor-legacy",
    name: "Tremor React legacy package",
    catalogMode: "legacy-docs-sitemap",
    catalogUrls: ["https://npm.tremor.so/sitemap.xml"],
    docsUrl: "https://npm.tremor.so/docs/getting-started/installation",
    previewUrl: "https://npm.tremor.so/docs",
    repositoryUrl: "https://github.com/tremorlabs/tremor-npm",
    licenseUrl: "https://github.com/tremorlabs/tremor-npm/blob/main/LICENSE",
    license: "Apache-2.0",
    guides: ["https://npm.tremor.so/docs/getting-started/installation"],
    coverage: "complete-live-legacy-docs",
    coverageNote: "30 still-live @tremor/react documentation capabilities; maintenance-stale, not officially deprecated.",
    redistribution: "permitted-with-license",
  },
  {
    id: "aceternity",
    name: "Aceternity UI",
    catalogMode: "documented-machine-index",
    catalogUrls: ["https://ui.aceternity.com/ai-recommendations"],
    docsUrl: "https://ui.aceternity.com/docs",
    previewUrl: "https://ui.aceternity.com/components",
    repositoryUrl: "",
    licenseUrl: "https://ui.aceternity.com/licence",
    license: "Aceternity per-item/Pro license; third-party items may differ",
    guides: [
      "https://ui.aceternity.com/docs/cli",
      "https://ui.aceternity.com/ai-recommendations",
      "https://ui.aceternity.com/changelog",
      "https://ui.aceternity.com/licence",
      "https://ui.aceternity.com/terms",
    ],
    coverage: "complete-to-ai-index",
    coverageNote:
      "Official AI index has 111 free components, one free hook and 207 Pro metadata entries; pricing copy says 200+ blocks and remains an unresolved upstream count conflict.",
    redistribution: "free-items-per-item-check;pro-no-source-redistribution",
  },
  {
    id: "magic-ui",
    name: "Magic UI Free",
    catalogMode: "registry",
    catalogUrls: ["https://magicui.design/r/registry.json"],
    docsUrl: "https://magicui.design/docs",
    previewUrl: "https://magicui.design/docs/components",
    repositoryUrl: "https://github.com/magicuidesign/magicui",
    licenseUrl: "https://github.com/magicuidesign/magicui/blob/main/LICENSE.md",
    license: "MIT",
    guides: [
      "https://magicui.design/docs/installation",
      "https://github.com/magicuidesign/magicui",
    ],
    coverage: "complete-free-registry",
    coverageNote: "247-item free Registry; Magic UI Pro has no public total manifest and is a separate lower-bound catalog.",
    redistribution: "permitted-with-license",
  },
  {
    id: "magic-ui-pro",
    name: "Magic UI Pro",
    catalogMode: "public-doc-pages-lower-bound",
    catalogUrls: [
      "https://pro.magicui.design/sitemap.xml",
      "https://pro.magicui.design/docs/sections/call-to-action",
      "https://pro.magicui.design/docs/sections/carousel",
      "https://pro.magicui.design/docs/sections/faq",
      "https://pro.magicui.design/docs/sections/feature-cards",
      "https://pro.magicui.design/docs/sections/feature-scroll",
      "https://pro.magicui.design/docs/sections/feature-slideshow",
      "https://pro.magicui.design/docs/sections/feature",
      "https://pro.magicui.design/docs/sections/footer",
      "https://pro.magicui.design/docs/sections/header",
      "https://pro.magicui.design/docs/sections/hero",
      "https://pro.magicui.design/docs/sections/pricing",
      "https://pro.magicui.design/docs/sections/social-proof",
    ],
    docsUrl: "https://pro.magicui.design/docs/installation",
    previewUrl: "https://pro.magicui.design/docs",
    repositoryUrl: "",
    licenseUrl: "https://pro.magicui.design/license",
    license: "Magic UI Pro commercial license; no source redistribution",
    guides: [
      "https://pro.magicui.design/docs/installation",
      "https://pro.magicui.design/license",
    ],
    coverage: "partial-public-docs-lower-bound",
    coverageNote: "95 exact public block slugs plus nine observed template names; official claims 50+ sections and 9+ templates without a public total Registry.",
    redistribution: "paid-no-source-redistribution;three-public-template-repositories",
  },
  {
    id: "react-bits",
    name: "React Bits Free",
    catalogMode: "repository-index",
    catalogUrls: [
      "https://api.github.com/repos/DavidHDev/react-bits/git/trees/main?recursive=1",
    ],
    docsUrl: "https://reactbits.dev/get-started/introduction",
    previewUrl: "https://reactbits.dev/",
    repositoryUrl: "https://github.com/DavidHDev/react-bits",
    licenseUrl: "https://github.com/DavidHDev/react-bits/blob/main/LICENSE.md",
    license: "MIT + Commons Clause for free React Bits",
    guides: [
      "https://reactbits.dev/get-started/installation",
      "https://github.com/DavidHDev/react-bits",
    ],
    coverage: "complete-free-repository",
    coverageNote: "166 free logical components, with four code variants deduplicated; Pro is a separate catalog.",
    redistribution: "free-commercial-use-with-commons-clause",
  },
  {
    id: "react-bits-pro",
    name: "React Bits Pro",
    catalogMode: "public-pro-docs-sitemap",
    catalogUrls: ["https://pro.reactbits.dev/sitemap.xml"],
    docsUrl: "https://pro.reactbits.dev/docs/introduction",
    previewUrl: "https://pro.reactbits.dev/docs",
    repositoryUrl: "",
    licenseUrl: "https://pro.reactbits.dev/license",
    license: "React Bits Pro commercial license; no source redistribution",
    guides: [
      "https://pro.reactbits.dev/docs/installation",
      "https://pro.reactbits.dev/license",
    ],
    coverage: "complete-public-pro-index",
    coverageNote: "702 paid assets: 134 components, 238 page blocks, 300 app UI blocks, 11 templates and 19 Agent Kit assets.",
    redistribution: "paid-no-source-redistribution",
  },
  {
    id: "tweakcn",
    name: "tweakcn",
    catalogMode: "theme-repository-index",
    catalogUrls: [
      "https://raw.githubusercontent.com/jnsahaj/tweakcn/main/utils/theme-presets.ts",
    ],
    discoveryUrls: ["https://tweakcn.com/community", "https://tweakcn.com/pricing"],
    docsUrl: "https://tweakcn.com/",
    previewUrl: "https://tweakcn.com/editor/theme",
    repositoryUrl: "https://github.com/jnsahaj/tweakcn",
    licenseUrl: "https://github.com/jnsahaj/tweakcn/blob/main/LICENSE",
    license: "Apache-2.0",
    guides: [
      "https://tweakcn.com/",
      "https://tweakcn.com/community",
      "https://tweakcn.com/pricing",
      "https://github.com/jnsahaj/tweakcn",
    ],
    coverage: "complete-default-presets-partial-dynamic-community",
    coverageNote:
      "All 42 defaultPresets are stored with their token source; anonymous community themes are dynamic and have no stable finite total.",
    redistribution: "permitted-with-license",
  },
  {
    id: "ai-elements",
    name: "Vercel AI Elements",
    catalogMode: "official-runtime-registry",
    catalogUrls: ["https://elements.ai-sdk.dev/api/registry/registry.json"],
    docsUrl: "https://elements.ai-sdk.dev/docs",
    previewUrl: "https://elements.ai-sdk.dev/components",
    repositoryUrl: "https://github.com/vercel/ai-elements",
    licenseUrl: "https://github.com/vercel/ai-elements/blob/main/LICENSE",
    license: "Apache-2.0",
    guides: [
      "https://elements.ai-sdk.dev/docs/setup",
      "https://elements.ai-sdk.dev/docs/usage",
      "https://elements.ai-sdk.dev/docs/troubleshooting",
      "https://github.com/vercel/ai-elements",
    ],
    coverage: "complete-official-runtime-registry",
    coverageNote:
      "Official /api/registry/registry.json lists every current component and example emitted by the deployed Registry route; docs-only headings are not counted as assets.",
    redistribution: "permitted-with-apache-2.0",
  },
  {
    id: "kibo-ui",
    name: "Kibo UI",
    catalogMode: "registry-plus-official-block-docs",
    catalogUrls: [
      "https://www.kibo-ui.com/r/registry.json",
      "https://api.github.com/repos/shadcnblocks/kibo/git/trees/main?recursive=1",
    ],
    docsUrl: "https://www.kibo-ui.com/docs",
    previewUrl: "https://www.kibo-ui.com/components",
    repositoryUrl: "https://github.com/shadcnblocks/kibo",
    licenseUrl: "https://github.com/shadcnblocks/kibo/blob/main/license.md",
    license: "MIT",
    guides: [
      "https://www.kibo-ui.com/docs",
      "https://www.kibo-ui.com/docs/usage",
      "https://www.kibo-ui.com/docs/troubleshooting",
      "https://github.com/shadcnblocks/kibo",
    ],
    coverage: "complete-current-registry-plus-public-block-docs",
    coverageNote:
      "The current Registry provides 40 components plus one style item. Official block MDX leaves are recorded as public metadata because their /r endpoints currently return 500 and are not source payloads. Shadcnblocks patterns are a separate product and are not counted as Kibo assets.",
    redistribution: "registry-source-mit;docs-metadata-only",
  },
  {
    id: "dice-ui",
    name: "Dice UI",
    catalogMode: "complete-current-radix-registry",
    catalogUrls: ["https://diceui.com/r/registry.json"],
    docsUrl: "https://diceui.com/docs/introduction",
    previewUrl: "https://diceui.com/docs/components",
    repositoryUrl: "https://github.com/sadmann7/diceui",
    licenseUrl: "https://github.com/sadmann7/diceui/blob/main/LICENSE",
    license: "MIT",
    guides: [
      "https://diceui.com/docs/introduction",
      "https://diceui.com/docs/components",
      "https://diceui.com/docs/changelog",
      "https://github.com/sadmann7/diceui",
    ],
    coverage: "complete-current-radix-registry",
    coverageNote:
      "The public r/registry.json is the current Radix Registry and contains UI modules, examples, hooks, utilities and internal component assets. Base/Radix Nova/Vega distributions remain a variant matrix rather than duplicated logical products.",
    redistribution: "permitted-with-mit",
  },
  {
    id: "animate-ui",
    name: "Animate UI",
    catalogMode: "complete-current-registry",
    catalogUrls: ["https://animate-ui.com/r/registry.json"],
    docsUrl: "https://animate-ui.com/docs",
    previewUrl: "https://animate-ui.com/docs/components",
    repositoryUrl: "https://github.com/imskyleen/animate-ui",
    licenseUrl: "https://github.com/imskyleen/animate-ui/blob/main/LICENSE.md",
    license: "MIT + Commons Clause",
    guides: [
      "https://animate-ui.com/docs/installation",
      "https://animate-ui.com/docs/accessibility",
      "https://animate-ui.com/docs/components",
      "https://animate-ui.com/docs/primitives",
      "https://github.com/imskyleen/animate-ui",
    ],
    coverage: "complete-current-registry",
    coverageNote:
      "The official Registry includes components, primitives, demos, hooks, utilities, styles and icon payloads. Logical/demo entries remain separate because they are separately installable Registry items.",
    redistribution: "application-use-with-commons-clause;no-component-resale",
  },
  {
    id: "motion-primitives",
    name: "Motion Primitives",
    catalogMode: "official-repository-registry",
    catalogUrls: [
      "https://raw.githubusercontent.com/ibelick/motion-primitives/main/public/c/registry.json",
    ],
    docsUrl: "https://motion-primitives.com/docs",
    previewUrl: "https://motion-primitives.com/docs",
    repositoryUrl: "https://github.com/ibelick/motion-primitives",
    licenseUrl: "https://github.com/ibelick/motion-primitives/blob/main/LICENCE.md",
    license: "MIT",
    guides: [
      "https://motion-primitives.com/docs/installation",
      "https://motion-primitives.com/docs",
      "https://github.com/ibelick/motion-primitives",
    ],
    coverage: "complete-official-repository-registry",
    coverageNote:
      "The deployed /c/registry.json may rate-limit automated clients; the identical public/c/registry.json in the official repository is the stable complete Registry source.",
    redistribution: "permitted-with-mit",
  },
];

export function getSource(id) {
  return UI_SOURCES.find((source) => source.id === id);
}
