export const UI_SOURCES = [
  {
    id: "shadcn",
    name: "shadcn/ui",
    catalogMode: "repository-index",
    catalogUrls: [
      "https://api.github.com/repos/shadcn-ui/ui/git/trees/main?recursive=1",
    ],
    docsUrl: "https://ui.shadcn.com/docs",
    previewUrl: "https://ui.shadcn.com/docs/components",
    repositoryUrl: "https://github.com/shadcn-ui/ui",
    licenseUrl: "https://github.com/shadcn-ui/ui/blob/main/LICENSE.md",
    license: "MIT",
    guides: [
      "https://github.com/shadcn-ui/ui/blob/main/skills/shadcn/SKILL.md",
      "https://github.com/shadcn-ui/ui/blob/main/skills/shadcn/customization.md",
      "https://github.com/shadcn-ui/ui/blob/main/skills/shadcn/registry.md",
    ],
    coverage: "partial",
    coverageNote:
      "官方未公开单一全量 item index；通过官方仓库树提取 Components、Examples、Blocks、Styles。",
    redistribution: "permitted-with-license",
  },
  {
    id: "coss",
    name: "coss/ui",
    catalogMode: "registry",
    catalogUrls: ["https://coss.com/ui/r/registry.json"],
    docsUrl: "https://coss.com/ui/docs",
    previewUrl: "https://coss.com/ui/particles",
    repositoryUrl: "https://github.com/cosscom/coss",
    licenseUrl: "https://github.com/cosscom/coss/blob/main/LICENSE",
    license: "MIT for apps/ui; repository default is AGPL-3.0",
    guides: [
      "https://coss.com/ui/docs/get-started",
      "https://coss.com/ui/docs/styling",
      "https://coss.com/ui/docs/radix-shadcn-migration",
      "https://coss.com/ui/docs/changelog",
      "https://coss.com/ui/docs/skills",
      "https://coss.com/ui/llms.txt",
    ],
    coverage: "complete",
    coverageNote: "官方 Registry 同时包含 primitives 与 Particles。",
    redistribution: "verify-file-is-under-apps-ui",
  },
  {
    id: "reui",
    name: "ReUI",
    catalogMode: "registry-and-repository-index",
    catalogUrls: [
      "https://reui.io/r/registry.json",
      "https://api.github.com/repos/keenthemes/reui/git/trees/main?recursive=1",
    ],
    docsUrl: "https://reui.io/docs",
    previewUrl: "https://reui.io/components",
    repositoryUrl: "https://github.com/keenthemes/reui",
    licenseUrl: "https://github.com/keenthemes/reui/blob/main/LICENSE",
    license: "MIT",
    guides: [
      "https://github.com/keenthemes/reui/blob/main/README.md",
      "https://reui.io/docs",
    ],
    coverage: "partial",
    coverageNote:
      "线上 Registry 当前重定向到一个 style；官方仓库树补齐其他 styles 与 1000+ c-* examples。",
    redistribution: "permitted-with-license",
  },
  {
    id: "tremor",
    name: "Tremor",
    catalogMode: "repository-index",
    catalogUrls: [
      "https://api.github.com/repos/tremorlabs/tremor/git/trees/main?recursive=1",
      "https://api.github.com/repos/tremorlabs/tremor-blocks/git/trees/main?recursive=1",
    ],
    docsUrl: "https://www.tremor.so/docs",
    previewUrl: "https://www.tremor.so/blocks",
    repositoryUrl: "https://github.com/tremorlabs",
    licenseUrl: "https://github.com/tremorlabs/tremor/blob/main/LICENSE",
    license: "Apache-2.0 for tremor; MIT for tremor-blocks repository",
    guides: [
      "https://www.tremor.so/docs/getting-started/installation",
      "https://github.com/tremorlabs/tremor",
      "https://github.com/tremorlabs/tremor-blocks",
    ],
    coverage: "partial",
    coverageNote:
      "Components 与 Blocks 分属两个官方仓库；通过仓库树归并，模板仓库另列。",
    redistribution: "verify-subproject-license",
  },
  {
    id: "aceternity",
    name: "Aceternity UI",
    catalogMode: "documented-machine-index",
    catalogUrls: ["https://ui.aceternity.com/ai-recommendations"],
    docsUrl: "https://ui.aceternity.com/docs",
    previewUrl: "https://ui.aceternity.com/components",
    repositoryUrl: "",
    licenseUrl: "https://ui.aceternity.com/licence",
    license: "Aceternity per-item/Pro license; third-party items may differ",
    guides: [
      "https://ui.aceternity.com/docs/cli",
      "https://ui.aceternity.com/ai-recommendations",
      "https://ui.aceternity.com/changelog",
      "https://ui.aceternity.com/licence",
      "https://ui.aceternity.com/terms",
    ],
    coverage: "complete",
    coverageNote:
      "官方 AI catalog 声明完整列出 free components、Pro components、templates、Pro blocks 与 hooks；免费与付费项分开保存。",
    redistribution: "free-items-per-item-check;pro-no-source-redistribution",
  },
  {
    id: "magic-ui",
    name: "Magic UI",
    catalogMode: "registry",
    catalogUrls: ["https://magicui.design/r/registry.json"],
    docsUrl: "https://magicui.design/docs",
    previewUrl: "https://magicui.design/docs/components",
    repositoryUrl: "https://github.com/magicuidesign/magicui",
    licenseUrl: "https://github.com/magicuidesign/magicui/blob/main/LICENSE.md",
    license: "MIT",
    guides: [
      "https://magicui.design/docs/installation",
      "https://github.com/magicuidesign/magicui",
    ],
    coverage: "complete",
    coverageNote: "官方 Registry 包含 components、examples 与 templates。",
    redistribution: "permitted-with-license",
  },
  {
    id: "react-bits",
    name: "React Bits",
    catalogMode: "repository-index",
    catalogUrls: [
      "https://api.github.com/repos/DavidHDev/react-bits/git/trees/main?recursive=1",
    ],
    docsUrl: "https://reactbits.dev/get-started/introduction",
    previewUrl: "https://reactbits.dev/",
    repositoryUrl: "https://github.com/DavidHDev/react-bits",
    licenseUrl: "https://github.com/DavidHDev/react-bits/blob/main/LICENSE",
    license: "MIT + Commons Clause for free React Bits; Pro is separate",
    guides: [
      "https://reactbits.dev/get-started/installation",
      "https://github.com/DavidHDev/react-bits",
      "https://pro.reactbits.dev/docs/installation",
    ],
    coverage: "partial",
    coverageNote:
      "免费目录由官方仓库 content/code variants 提取；React Bits Pro 是独立付费 Registry，不能混入免费源码。",
    redistribution: "free-commercial-use-with-commons-clause;pro-license-separate",
  },
  {
    id: "tweakcn",
    name: "tweakcn",
    catalogMode: "theme-repository-index",
    catalogUrls: [
      "https://raw.githubusercontent.com/jnsahaj/tweakcn/main/utils/theme-presets.ts",
    ],
    docsUrl: "https://tweakcn.com/",
    previewUrl: "https://tweakcn.com/editor/theme",
    repositoryUrl: "https://github.com/jnsahaj/tweakcn",
    licenseUrl: "https://github.com/jnsahaj/tweakcn/blob/main/LICENSE",
    license: "Apache-2.0",
    guides: [
      "https://tweakcn.com/",
      "https://github.com/jnsahaj/tweakcn",
    ],
    coverage: "partial",
    coverageNote:
      "完整收录官方仓库 defaultPresets；社区动态主题没有稳定全量 API，另保留 editor/community 入口。",
    redistribution: "permitted-with-license",
  },
];

export function getSource(id) {
  return UI_SOURCES.find((source) => source.id === id);
}
